---
title: "Intro_to_CyTOF"
output: html_document
---

```{r Packages nessecary for mass cytometry analysis}

cran_packages <- c("scales", "ggplot2", "dplyr", "ggridges", "RColorBrewer", "MASS", "Rtsne", "kohonen", "miscTools", "gplots", "Radviz", "igraph", "statmod", "devtools", "uwot", "cowplot", "limma", "matrixcalc", "plotrix", "JPEN", "VCA")

bioc_packages <- c("flowCore", "ConsensusClusterPlus", "cydar", "CATALYST", "ncdfFlow", "edgeR", "HDCytoData")

github_packages <- c("nolanlab/cytofCore", "JinmiaoChenLab/cytofkit2", "cytolab/mem", "biosurf/cyCombine")

```

```{r Load the libraries}

## ArcSinh transformation libraries ##
library(MASS)

## General ##
library(flowCore)
library(tidyverse)
library(RColorBrewer)
library(ggplot2)
library(cowplot)
library(reshape2)
library(purrr)
library(stringr)
library(ggridges)

```


```{r Load the files}

FCS_file_list <- list.files(path = "~/SLE/3TR/Tutorial/Files/", pattern = ".fcs", full.names = TRUE, ignore.case = TRUE)

## Load the first FCS file from the list ## 
FCS_File_1 <- read.FCS(filename = FCS_file_list[1], transformation = FALSE, truncate_max_range = FALSE)

## To load all files: ##
# FCS_Files <- read.flowSet(files = FCS_file_list, transformation = FALSE, truncate_max_range = FALSE)

## Extract the expression matrix ##
Exp_matrix <- FCS_File_1@exprs
FCS_File_1@parameters@data

## Make the files more readable ##
Markers <- gsub(pattern = ".*_", replacement = "", x = as.vector(FCS_File_1@parameters@data$desc)) ## The tutorial has it with @ FCS_Files@parameters@data$desc
colnames(Exp_matrix)[which(!is.na(Markers))] <- Markers[which(!is.na(Markers))] ## Re do this with the tidyverse

```

```{r Data preprocessing}

Pregating_Channels <- c("Bead", "DNA1", "DNA2", "Dead", "Event_length")

Lineage_Channels <- c("CD57", "CD19", "CD4", "CD8", "IgD", "CD11c",
                      "CD16", "CD3", "CD38", "CD27", "CD14", "CXCR5",
                      "CCR7", "CD45RA", "CD20", "CD127", "CD33", "CD28", 
                      "CD161", "TCRgd", "CD123", "CD56", "HLADR", "CD25")

Instrument_Channels <- c("Time", "Event_length", "Center", "Offset", "Width", "Residual")

```

```{r Check for randomised values}

# 2. Helper functions
is_whole <- function(x, tol = .Machine$double.eps^0.5) {
  abs(x - round(x)) < tol
}

derandomize <- function(mat, measure_ch, other_ch) {
  derand <- ceiling(mat[, measure_ch])
  cbind(derand, mat[, other_ch, drop = FALSE])
}

## Apply the checks and derandomisation ##
non_int_counts <- sum(!is_whole(Exp_matrix[, c(Pregating_Channels, 
                                               Lineage_Channels)]))

## Show summary ##
table_wholeness <- table(is_whole(Exp_matrix[, c(Pregating_Channels, 
                                                 Lineage_Channels)]))

## Derandomize measured channels if necessary ##
Exp_matrix_clean <- derandomize(
  Exp_matrix,
  measure_ch = c(Lineage_Channels, Pregating_Channels),
  other_ch = Instrument_Channels)


```

```{r ArcSinh transformation}

## Make arcsinh transformed expression matrix using a cofactor of 5##
## (with the exception of time and event_length, which should remain linear) ##
selections <- c(Lineage_Channels, Pregating_Channels[1:4], Instrument_Channels)

Exp_data <- Exp_matrix %>% 
  as_tibble() %>% 
  dplyr::select(all_of(selections))

Exp_data_trans <- Exp_matrix %>% 
  as_tibble() %>% 
  mutate(across(.cols = all_of(c(Lineage_Channels, Pregating_Channels[1:4])), 
                .fns = ~ asinh(.x / 5), 
                .names = "{.col}")) %>% 
  dplyr::select(all_of(selections))

## Plot two-marker example of transformation effect ##
p1 <- ggplot(Exp_data, aes(x = CD8, y = CD4)) +
  geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
  geom_density2d() +
  ggtitle('CD4 vs CD8') +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

p2 <- ggplot(Exp_data_trans, aes(x = CD8, y = CD4)) +
  geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
  geom_density2d() +
  ggtitle('CD4 vs CD8 (transformed counts)') +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

plot_grid(p1, p2, align = 'v', scale = 0.9)

```

```{r Ion counts}

Exp_data_long <- Exp_data %>%
  mutate(Cell_id = row_number()) %>% 
  pivot_longer(cols = all_of(Lineage_Channels),
               names_to = "Channel",
               values_to = "Value") %>% 
  mutate(Origin = "Raw")

Exp_data_trans_long <- Exp_data_trans %>%
  mutate(Cell_id = row_number()) %>% 
  pivot_longer(cols = all_of(Lineage_Channels),
               names_to = "Channel",
               values_to = "Value") %>% 
  mutate(Origin = "Transformed")

## Combine the two dfs ##
Exp_Comparison <- rbind(Exp_data_long, Exp_data_trans_long)

## Plot them ##
ggplot(Exp_Comparison, aes(x = Channel, y = Value, color = Channel)) +
  geom_boxplot(outlier.size = 0.05) +
  facet_wrap(~ Origin, scales = "free", ncol = 1) +
  labs(x = "Channel", y = "Value",
       title = "Raw vs asinh-transformed distributions") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5))

```

```{r Pregating prep}

Expr_set <- FCS_file_list %>% 
  set_names() %>% 
  map_dfr(function(file) {
    
    ff <- read.FCS(filename = file, 
                   transformation = FALSE, 
                   truncate_max_range = FALSE)
    
    c_matrix <- exprs(ff)
    
    desc_data <- ff@parameters@data$desc
    markers <- str_replace(desc_data, ".*_", "")
    idx <- which(!is.na(markers))
    
    colnames(c_matrix)[idx] <- markers[idx]
    
    set.seed(134)
    samp_idx <- sample(nrow(c_matrix), 10000)
    sampled  <- c_matrix[samp_idx, , drop = FALSE]
    
    sampled %>% 
      as_tibble() %>% 
      mutate(Origin = basename(file))
    
  })

Expr_set_trans <- Expr_set %>%
  mutate(across(.cols = all_of(c(Pregating_Channels[1:4],
                                 Lineage_Channels)),
                .fns  = ~ asinh(.x / 5))) %>% 
  select(all_of(c(Pregating_Channels[1:4], Lineage_Channels)),
         all_of(Instrument_Channels), 
         Origin)


```

```{r Visualise pregating channels}

cols <- brewer.pal(length(Pregating_Channels), "Set1")
names(cols) <- Pregating_Channels

Expr_set_trans %>% 
  select(Origin, all_of(Pregating_Channels)) %>% 
  pivot_longer(cols = all_of(Pregating_Channels), 
               names_to = "Channel", 
               values_to = "Value") %>% 
  ggplot(., aes(x = Value, y = Origin, colour = Channel, fill = Channel)) +
  geom_density_ridges2() +
  facet_wrap(~ Channel, ncol = 5, scales = "free_x") +
  scale_color_manual(values = cols) +
  scale_fill_manual(values  = alpha(cols, 0.4)) +
  theme_bw() +
  theme(axis.text.y = element_blank(), 
        strip.text = element_text(face = "bold")) +
  ylab("")
  
```

```{r Gating for cells}
## Cells vs Beads ##

h <- Expr_set_trans %>%
  summarize(h1 = bandwidth.nrd(Bead),
            h2 = bandwidth.nrd(DNA1)) %>%
  summarize(h = max(h1, h2)) %>%
  pull(h)

Plot_1 <- Expr_set_trans %>% 
ggplot(aes(x = Bead, y = DNA1)) +
      geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
      geom_density2d(h = h) +
      theme_bw()

Gate_1 <- list(left = 0, right = 2.5, lower = 5, upper = 8.5)

Cells_1 <- Expr_set_trans %>%
  filter(Bead < Gate_1$right, DNA1 > Gate_1$lower, DNA1 < Gate_1$upper)

Pct_in_gate <- nrow(Cells_1) / nrow(Expr_set_trans) * 100

Plot_1 +
  geom_rect(data = NULL, aes(xmin = Gate_1$left, 
                             xmax = Gate_1$right, 
                             ymin = Gate_1$lower, 
                             ymax = Gate_1$upper), 
            inherit.aes = FALSE, fill = NA, colour = "red", linetype = "dashed") +
  annotate("text", x = Gate_1$right + 1, y = mean(c(Gate_1$lower, Gate_1$upper)), 
           label = sprintf("Cells: %.2f%%", Pct_in_gate), 
           colour = "red") + 
  theme_bw()

```

```{r Gating for intact cells}
## Cells vs Beads ##

Plot_2 <- Cells_1 %>%
  ggplot(aes(x = DNA1, y = DNA2)) +
  geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
  coord_cartesian(xlim = c(5, 8), 
                  ylim = c(5.5, 8.5)) +
  geom_density2d() +
  theme_bw()

Gate_2 <- list(left = 5.75, right = 7.3, lower = 6.35, upper = 7.95)

Cells_2 <- Cells_1 %>%
  filter(DNA1 > Gate_2$left, 
         DNA1 < Gate_2$right, 
         DNA2 > Gate_2$lower, 
         DNA2 < Gate_2$upper)

Pct_intact <- nrow(Cells_2) / nrow(Cells_1) * 100

Plot_2 +
  geom_rect(data = NULL, aes(xmin = Gate_2$left, 
                             xmax = Gate_2$right, 
                             ymin = Gate_2$lower, 
                             ymax = Gate_2$upper), 
            inherit.aes = FALSE, fill = NA, colour = "red", linetype = "dashed") +
  annotate("text", x = Gate_2$right + 0.4, y = mean(c(Gate_2$lower, Gate_2$upper)), 
           label = sprintf("Cells: %.2f%%", Pct_intact), 
           colour = "red") + 
  theme_bw()

```

```{r Gating for singlets}
## Cells vs Beads ##

Plot_3 <- Cells_2 %>%
  ggplot(aes(x = Event_length, y = DNA1)) +
  geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
  coord_cartesian(ylim = c(0, 8)) +
  geom_density2d() +
  theme_bw()

Gate_3 <- list(left = 12, right = 22, lower = 5.65, upper = 7.35)

Cells_3 <- Cells_2 %>%
  filter(Event_length > Gate_3$left, 
         Event_length < Gate_3$right)

Pct_singlets <- nrow(Cells_3) / nrow(Cells_2) * 100

Plot_3 +
  geom_rect(data = NULL, aes(xmin = Gate_3$left, 
                             xmax = Gate_3$right, 
                             ymin = Gate_3$lower, 
                             ymax = Gate_3$upper), 
            inherit.aes = FALSE, fill = NA, colour = "red", linetype = "dashed") +
  annotate("text", y = Gate_2$lower - 1, x = mean(c(Gate_3$left, Gate_3$right)), 
           label = sprintf("Intact singlets: %.2f%%", Pct_singlets), 
           colour = "red") + 
  theme_bw()

```

```{r Gating for live cells}
## Cells vs Beads ##

Plot_4 <- Cells_2 %>%
  ggplot(aes(x = Dead, y = DNA1)) +
  geom_point(color = 'grey', size = 0.05, alpha = 0.6) +
  coord_cartesian(ylim = c(0, 8)) +
  geom_density2d() +
  theme_bw()

Gate_4 <- list(left = 0, right = 3.5, lower = 5.65, upper = 7.35)

Cells_4 <- Cells_3 %>%
  filter(Dead < Gate_4$right)

Pct_live <- nrow(Cells_4) / nrow(Cells_3) * 100

Plot_4 +
  geom_rect(data = NULL, aes(xmin = Gate_4$left, 
                             xmax = Gate_4$right, 
                             ymin = Gate_4$lower, 
                             ymax = Gate_4$upper), 
            inherit.aes = FALSE, fill = NA, colour = "red", linetype = "dashed") +
  annotate("text", y = Gate_2$lower - 1, x = mean(c(Gate_4$left, Gate_4$right)), 
           label = sprintf("Live and intact singlets: %.2f%%", Pct_live), 
           colour = "red") + 
  theme_bw()

```


```{r Print live cell percentage for each sample}

for (orgn in unique(Expr_set_trans$Origin)) {
  
  Current_sample <- Expr_set_trans %>% 
    filter(Origin == orgn)
  
  Current_live <- Cells_4 %>% 
    filter(Origin == orgn)
  
  print(paste0("Total recovery for ", orgn, ": ", 
               round(nrow(Current_live) / nrow(Current_sample) * 100, 
                     digits = 2), "%", sep = ""))
}

```

